name: Deploy to Production

on:
  push:
    branches:
      - main


jobs:
  production-deploy:
    name: ðŸš€ Deploy to Production (ptgvn.site)
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get Latest Code
      uses: actions/checkout@v3

    - name: ðŸ“‚ Deploy to Production via SSH
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        REMOTE_HOST: ptgvn.site
        REMOTE_USER: ptgvnsit
        TARGET: /home/ptgvnsit/ptgvn.site/
        EXCLUDE: ".git*, .github/, README.md, readme.md, .gitignore, GITHUB_SSH_KEY.txt"
